### ISSUE TITLE
simpla/ajax/export_to_ICML_retailCRM.php

### ISSUE THREAD

**Issue by osben** [XOlegator/simpla-test#3]
а где собственно файл require_once ('../../integration/Tools.php');

**Comment by XOlegator** [comment]
Код из скрипта Tools.php перекочевал в основной класс Retail.php - по-идее, не должно уже нигде остаться ссылок на этот файл

**Comment by XOlegator** [comment]
Сейчас внёс исправление. Спасибо, что заметили эту ошибку! Для генерации ICML файла оставалась попытка использовать старый класс, который уже упразднён
